name: granter_challenger
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  get_cli: ^1.7.1
  
  

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  

flutter: 
  assets: 
    - assets/jsons/products.json
  uses-material-design: true

